In [2]:
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
from folium.features import GeoJson, GeoJsonTooltip, GeoJsonPopup
from folium.plugins import TimeSliderChoropleth
import folium
import seaborn as sns
import os
from branca.colormap import linear
from LocalFunctions import get_hex_colors
%matplotlib inline

In [3]:
gdf = gpd.read_file(r'..\Datasets Italia\milano-grid.geojson', mask='geojson')

cdf10min = pd.read_csv('..\Datasets Italia\Telecommunications - SMS, Call, Internet - MI\10Mins-Consolidated.csv')

In [4]:
cdf = pd.read_csv('..\Datasets Italia\Telecommunications - SMS, Call, Internet - MI\Hourly-Consolidated-with-cellid.txt',delimiter='\t')

In [5]:
cdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239998 entries, 0 to 239997
Data columns (total 10 columns):
cellId            239998 non-null int64
timeIntervalts    239998 non-null object
timeInterval      239998 non-null int64
SMSin             239998 non-null float64
SMSout            239998 non-null float64
callIn            239998 non-null float64
callOut           239998 non-null float64
internet          239998 non-null float64
SMS               239998 non-null float64
call              239998 non-null float64
dtypes: float64(7), int64(2), object(1)
memory usage: 18.3+ MB

In [6]:
cdf.head()

,cellId,timeIntervalts,timeInterval,SMSin,SMSout,callIn,callOut,internet,SMS,call
0,1,2013-12-29 00:00:00+01:00,27667681800000,11.614903,6.186866,5.204528,5.640638,205.769225,17.801769,10.845166
1,1,2013-12-29 01:00:00+01:00,15217584000000,6.222223,2.949818,3.222296,3.576615,108.364250,9.172042,6.798911
2,1,2013-12-29 02:00:00+01:00,12450302400000,4.761782,3.334068,2.709599,3.281181,91.990481,8.095851,5.990780
3,1,2013-12-29 03:00:00+01:00,13834195200000,4.755038,3.279420,3.112042,4.580512,113.159767,8.034458,7.692554
4,1,2013-12-29 04:00:00+01:00,15217366200000,5.370352,3.094265,2.262312,2.347458,109.195008,8.464617,4.609771

In [7]:
cdf['cellId'].drop_duplicates()

0             1
24            2
48            3
72            4
96            5
          ...
239878     9996
239902     9997
239926     9998
239950     9999
239974    10000
Name: cellId, Length: 10000, dtype: int64

In [8]:
cdf2 = cdf.copy()

In [9]:
cdf2 = cdf2.reset_index()

In [10]:
cdf2['timeIntervalts'] = pd.to_datetime(cdf2['timeIntervalts'])

In [11]:
cdf2 = cdf2.set_index(['cellId','timeIntervalts'])

In [12]:
cdf2.head()

                                  index    timeInterval      SMSin    SMSout  \
cellId timeIntervalts
1      2013-12-29 00:00:00+01:00      0  27667681800000  11.614903  6.186866
       2013-12-29 01:00:00+01:00      1  15217584000000   6.222223  2.949818
       2013-12-29 02:00:00+01:00      2  12450302400000   4.761782  3.334068
       2013-12-29 03:00:00+01:00      3  13834195200000   4.755038  3.279420
       2013-12-29 04:00:00+01:00      4  15217366200000   5.370352  3.094265

                                    callIn   callOut    internet        SMS  \
cellId timeIntervalts
1      2013-12-29 00:00:00+01:00  5.204528  5.640638  205.769225  17.801769
       2013-12-29 01:00:00+01:00  3.222296  3.576615  108.364250   9.172042
       2013-12-29 02:00:00+01:00  2.709599  3.281181   91.990481   8.095851
       2013-12-29 03:00:00+01:00  3.112042  4.580512  113.159767   8.034458
       2013-12-29 04:00:00+01:00  2.262312  2.347458  109.195008   8.464617

                                       call
cellId timeIntervalts
1      2013-12-29 00:00:00+01:00  10.845166
       2013-12-29 01:00:00+01:00   6.798911
       2013-12-29 02:00:00+01:00   5.990780
       2013-12-29 03:00:00+01:00   7.692554
       2013-12-29 04:00:00+01:00   4.609771

cdf2 = cdf2.groupby([pd.Grouper(level='cellId'),pd.Grouper(level='timeInterval',freq='H')]).sum()

In [13]:
cdf2['hour'] = cdf2.reset_index().set_index('timeIntervalts').index.hour

In [14]:
cdf2

                                   index    timeInterval      SMSin  \
cellId timeIntervalts
1      2013-12-29 00:00:00+01:00       0  27667681800000  11.614903
       2013-12-29 01:00:00+01:00       1  15217584000000   6.222223
       2013-12-29 02:00:00+01:00       2  12450302400000   4.761782
       2013-12-29 03:00:00+01:00       3  13834195200000   4.755038
       2013-12-29 04:00:00+01:00       4  15217366200000   5.370352
...                                  ...             ...        ...
10000  2013-12-29 19:00:00+01:00  239993  30433977000000  27.862764
       2013-12-29 20:00:00+01:00  239994  20750777400000  15.187433
       2013-12-29 21:00:00+01:00  239995  20750215800000  24.075500
       2013-12-29 22:00:00+01:00  239996  24901110600000  21.115529
       2013-12-29 23:00:00+01:00  239997  29051204400000  23.994500

                                     SMSout     callIn    callOut    internet  \
cellId timeIntervalts
1      2013-12-29 00:00:00+01:00   6.186866   5.204528   5.640638  205.769225
       2013-12-29 01:00:00+01:00   2.949818   3.222296   3.576615  108.364250
       2013-12-29 02:00:00+01:00   3.334068   2.709599   3.281181   91.990481
       2013-12-29 03:00:00+01:00   3.279420   3.112042   4.580512  113.159767
       2013-12-29 04:00:00+01:00   3.094265   2.262312   2.347458  109.195008
...                                     ...        ...        ...         ...
10000  2013-12-29 19:00:00+01:00  19.290816  21.308455  25.513559  494.887836
       2013-12-29 20:00:00+01:00  10.354212  11.834990  13.847210  297.898329
       2013-12-29 21:00:00+01:00  16.685875  14.957908  15.870766  392.917872
       2013-12-29 22:00:00+01:00  17.211963  17.224146  17.066921  368.219706
       2013-12-29 23:00:00+01:00  18.118360  13.848778  16.035157  392.155027

                                        SMS       call  hour
cellId timeIntervalts
1      2013-12-29 00:00:00+01:00  17.801769  10.845166     0
       2013-12-29 01:00:00+01:00   9.172042   6.798911     1
       2013-12-29 02:00:00+01:00   8.095851   5.990780     2
       2013-12-29 03:00:00+01:00   8.034458   7.692554     3
       2013-12-29 04:00:00+01:00   8.464617   4.609771     4
...                                     ...        ...   ...
10000  2013-12-29 19:00:00+01:00  47.153580  46.822014    19
       2013-12-29 20:00:00+01:00  25.541645  25.682200    20
       2013-12-29 21:00:00+01:00  40.761375  30.828674    21
       2013-12-29 22:00:00+01:00  38.327491  34.291067    22
       2013-12-29 23:00:00+01:00  42.112860  29.883935    23

[239998 rows x 10 columns]

In [15]:
cdf3 = cdf2[['internet','SMS','call','hour']]

In [16]:
cdf3 = cdf3.reset_index()

In [17]:
cdf3 = cdf3[['cellId', 'internet', 'SMS', 'call', 'hour']]

In [18]:
cdf3

        cellId    internet        SMS       call  hour
0            1  205.769225  17.801769  10.845166     0
1            1  108.364250   9.172042   6.798911     1
2            1   91.990481   8.095851   5.990780     2
3            1  113.159767   8.034458   7.692554     3
4            1  109.195008   8.464617   4.609771     4
...        ...         ...        ...        ...   ...
239993   10000  494.887836  47.153580  46.822014    19
239994   10000  297.898329  25.541645  25.682200    20
239995   10000  392.917872  40.761375  30.828674    21
239996   10000  368.219706  38.327491  34.291067    22
239997   10000  392.155027  42.112860  29.883935    23

[239998 rows x 5 columns]

In [19]:
perCellid = cdf3.groupby('cellId').sum()

In [20]:
perCellid

            internet          SMS        call  hour
cellId
1        4269.373196   351.001279  257.139544   276
2        4288.001873   355.895721  261.432074   276
3        4307.831362   361.105661  266.001302   276
4        4215.414898   336.824439  244.706156   276
5        3844.248238   313.350959  228.955970   276
...              ...          ...         ...   ...
9996    15291.749070  1044.289497  841.478633   276
9997    16827.469852  1130.565588  913.049328   276
9998    16549.264896  1112.403660  898.322634   276
9999    10267.016099   798.373576  647.196149   276
10000    7993.207239   754.845640  610.940520   276

[10000 rows x 4 columns]

In [21]:
mergedf = gdf.merge(perCellid,on='cellId',how='outer')

In [22]:
mergedf

,cellId,geometry,internet,SMS,call,hour
0,1,"POLYGON ((9.01149 45.35880, 9.01449 45.35880, ...",4269.373196,351.001279,257.139544,276
1,2,"POLYGON ((9.01449 45.35880, 9.01749 45.35880, ...",4288.001873,355.895721,261.432074,276
2,3,"POLYGON ((9.01749 45.35880, 9.02049 45.35880, ...",4307.831362,361.105661,266.001302,276
3,4,"POLYGON ((9.02049 45.35880, 9.02349 45.35880, ...",4215.414898,336.824439,244.706156,276
4,5,"POLYGON ((9.02349 45.35880, 9.02649 45.35880, ...",3844.248238,313.350959,228.955970,276
...,...,...,...,...,...,...
9995,9996,"POLYGON ((9.29763 45.56783, 9.30064 45.56782, ...",15291.749070,1044.289497,841.478633,276
9996,9997,"POLYGON ((9.30064 45.56782, 9.30365 45.56781, ...",16827.469852,1130.565588,913.049328,276
9997,9998,"POLYGON ((9.30365 45.56781, 9.30667 45.56780, ...",16549.264896,1112.403660,898.322634,276
9998,9999,"POLYGON ((9.30667 45.56780, 9.30968 45.56779, ...",10267.016099,798.373576,647.196149,276
9999,10000,"POLYGON ((9.30968 45.56779, 9.31269 45.56779, ...",7993.207239,754.845640,610.940520,276

In [23]:
colormap = linear.Reds_09.scale(
    mergedf.SMS.min(),
    mergedf.SMS.max())

print(colormap(5.0))

colormap

#fff5f0ff

In [24]:
sdf_dict = perCellid['SMS']
sdf_dict.head()

cellId
1    351.001279
2    355.895721
3    361.105661
4    336.824439
5    313.350959
Name: SMS, dtype: float64

In [25]:
colormap(sdf_dict[1])

'#fff5efff'

In [26]:
m = folium.Map(location=[45.46440063879739, 9.194880739442098],tiles="Stamen Toner" #"cartodbpositron"
               , zoom_start=12)

tooltip=GeoJsonTooltip(
    fields=["cellId", "SMS"],
    aliases=["cellId", "SMS"],
    localize=True,
    sticky=False,
    labels=True,
    style="""
        background-color: #F0EFEF;
        border: 2px solid black;
        border-radius: 3px;
        box-shadow: 3px;
    """,
    max_width=800,
)

popup=GeoJsonPopup(
    fields=["cellId", "SMS"], 
    aliases=["cellId", "SMS"], 
    localize=True, 
    labels=True, 
    style="background-color: yellow;")

g = folium.GeoJson(
    mergedf[['cellId','SMS','geometry']],
    name = 'SMSs',
    style_function=lambda x: {
        'fillColor': colormap(sdf_dict[x['properties']['cellId']]),
        'color': 'black',
        'weight': 0.4,
#         'dashArray': '5, 5',
        'fillOpacity': 0.8,
        'line_opacity':0.2,
    },
    tooltip=tooltip,
    popup=popup
).add_to(m)

folium.LayerControl().add_to(m)

m.save('AllGrids.html')

In [27]:
cdf2

                                   index    timeInterval      SMSin  \
cellId timeIntervalts
1      2013-12-29 00:00:00+01:00       0  27667681800000  11.614903
       2013-12-29 01:00:00+01:00       1  15217584000000   6.222223
       2013-12-29 02:00:00+01:00       2  12450302400000   4.761782
       2013-12-29 03:00:00+01:00       3  13834195200000   4.755038
       2013-12-29 04:00:00+01:00       4  15217366200000   5.370352
...                                  ...             ...        ...
10000  2013-12-29 19:00:00+01:00  239993  30433977000000  27.862764
       2013-12-29 20:00:00+01:00  239994  20750777400000  15.187433
       2013-12-29 21:00:00+01:00  239995  20750215800000  24.075500
       2013-12-29 22:00:00+01:00  239996  24901110600000  21.115529
       2013-12-29 23:00:00+01:00  239997  29051204400000  23.994500

                                     SMSout     callIn    callOut    internet  \
cellId timeIntervalts
1      2013-12-29 00:00:00+01:00   6.186866   5.204528   5.640638  205.769225
       2013-12-29 01:00:00+01:00   2.949818   3.222296   3.576615  108.364250
       2013-12-29 02:00:00+01:00   3.334068   2.709599   3.281181   91.990481
       2013-12-29 03:00:00+01:00   3.279420   3.112042   4.580512  113.159767
       2013-12-29 04:00:00+01:00   3.094265   2.262312   2.347458  109.195008
...                                     ...        ...        ...         ...
10000  2013-12-29 19:00:00+01:00  19.290816  21.308455  25.513559  494.887836
       2013-12-29 20:00:00+01:00  10.354212  11.834990  13.847210  297.898329
       2013-12-29 21:00:00+01:00  16.685875  14.957908  15.870766  392.917872
       2013-12-29 22:00:00+01:00  17.211963  17.224146  17.066921  368.219706
       2013-12-29 23:00:00+01:00  18.118360  13.848778  16.035157  392.155027

                                        SMS       call  hour
cellId timeIntervalts
1      2013-12-29 00:00:00+01:00  17.801769  10.845166     0
       2013-12-29 01:00:00+01:00   9.172042   6.798911     1
       2013-12-29 02:00:00+01:00   8.095851   5.990780     2
       2013-12-29 03:00:00+01:00   8.034458   7.692554     3
       2013-12-29 04:00:00+01:00   8.464617   4.609771     4
...                                     ...        ...   ...
10000  2013-12-29 19:00:00+01:00  47.153580  46.822014    19
       2013-12-29 20:00:00+01:00  25.541645  25.682200    20
       2013-12-29 21:00:00+01:00  40.761375  30.828674    21
       2013-12-29 22:00:00+01:00  38.327491  34.291067    22
       2013-12-29 23:00:00+01:00  42.112860  29.883935    23

[239998 rows x 10 columns]

In [28]:
timedf = cdf2[['SMS']].reset_index()

In [29]:
timedf

        cellId            timeIntervalts        SMS
0            1 2013-12-29 00:00:00+01:00  17.801769
1            1 2013-12-29 01:00:00+01:00   9.172042
2            1 2013-12-29 02:00:00+01:00   8.095851
3            1 2013-12-29 03:00:00+01:00   8.034458
4            1 2013-12-29 04:00:00+01:00   8.464617
...        ...                       ...        ...
239993   10000 2013-12-29 19:00:00+01:00  47.153580
239994   10000 2013-12-29 20:00:00+01:00  25.541645
239995   10000 2013-12-29 21:00:00+01:00  40.761375
239996   10000 2013-12-29 22:00:00+01:00  38.327491
239997   10000 2013-12-29 23:00:00+01:00  42.112860

[239998 rows x 3 columns]

In [30]:
timedf["timeIntervalts"] = (timedf["timeIntervalts"].astype(int)// 10**9).astype('U10')
timedf.head()

   cellId timeIntervalts        SMS
0       1     1388271600  17.801769
1       1     1388275200   9.172042
2       1     1388278800   8.095851
3       1     1388282400   8.034458
4       1     1388286000   8.464617

In [31]:
%%time
data_to_color = "SMS"
cells = list(timedf["cellId"].unique())
dates = list(timedf["timeIntervalts"].unique())
colors = get_hex_colors.get_hex_colors(timedf, data_to_color, cmap = matplotlib.cm.Reds)#, log = True) # color dict that get's created from our get_hex_colors based on the values you want to plot
timedf["COLORS"] = timedf[data_to_color].map(colors) # create a colum in the df so that we can iterate and create the styledict

Wall time: 1min 31s

styledict = {}

%time
# iterate the populate the styledict
for cell in [1]:
    styledict[str(cell)] = {date: {'color': timedf[(timedf["cellId"] == cell) & (timedf["timeIntervalts"] == date)]["COLORS"].values[0],
                                   'opacity': 0.6} for date in dates}

In [32]:
styledict = {}
for cell in cells:
    #print(row)
    styledict[str(cell)] = {row['timeIntervalts']: {'color': row['COLORS'],
                                   'opacity': 0.8,'weight': 0.4,'fillOpacity': 0.8,'line_opacity':0.2,} 
                            for index, row in timedf[timedf['cellId']==cell].iterrows()}

In [33]:
len(styledict)

10000

In [ ]:
# creates and renders the Folium map
m = folium.Map(location=[45.46440063879739, 9.194880739442098],tiles="Stamen Toner" #"cartodbpositron"
               , zoom_start=12)

g = TimeSliderChoropleth(
    gdf.set_index("cellId").to_json(), # get's the coordinates for each id 
    styledict = styledict, # styledict contains for each id the timestamp and the color to plot.
    name = 'TimeSlider',
    overlay = False
)

m.add_child(g)
m.save('TimeSliderChoropleth1.html')

m

In [35]:
%%time
data_to_color = "SMS"
cells = list(timedf["cellId"].unique())
dates = list(timedf["timeIntervalts"].unique())
colors = get_hex_colors.get_hex_colors(timedf, data_to_color, cmap = matplotlib.cm.Reds, log = True) # color dict that get's created from our get_hex_colors based on the values you want to plot
timedf["COLORS"] = timedf[data_to_color].map(colors) # create a colum in the df so that we can iterate and create the styledict

C:\Users\kisha\Anaconda3\lib\site-packages\matplotlib\colors.py:509: UserWarning: Warning: converting a masked element to nan.
  xa = np.array([X])
C:\Users\kisha\Anaconda3\lib\site-packages\matplotlib\colors.py:527: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

Wall time: 2min 24s

In [36]:
styledict = {}
for cell in cells:
    #print(row)
    styledict[str(cell)] = {row['timeIntervalts']: {'color': row['COLORS'],
                                   'opacity': 0.6,'weight': 0.4} 
                            for index, row in timedf[timedf['cellId']==cell].iterrows()}

In [ ]:
# creates and renders the Folium map
m = folium.Map(location=[45.46440063879739, 9.194880739442098],tiles="Stamen Toner" #"cartodbpositron"
               , zoom_start=12)

g = TimeSliderChoropleth(
    gdf.set_index("cellId").to_json(), # get's the coordinates for each id 
    styledict = styledict, # styledict contains for each id the timestamp and the color to plot.
    name = 'TimeSlider',
    overlay = False
)

m.add_child(g)
m.save('TimeSliderChoropleth2.html')

m

In [38]:
cdfD = pd.read_csv('..\Datasets Italia\Telecommunications - SMS, Call, Internet - MI\Daily-Consolidated-with-cellid.txt',delimiter='\t')

In [39]:
cdfD.head()

,cellId,timeIntervalts,timeInterval,SMSin,SMSout,callIn,callOut,internet,SMS,call
0,1,2013-11-01 00:00:00+01:00,199195675200000,78.709755,45.886570,41.108567,48.245378,1507.048349,124.596325,89.353945
1,1,2013-11-02 00:00:00+01:00,199208116800000,86.415810,43.875946,47.891016,53.590637,1515.641856,130.291756,101.481653
2,1,2013-11-03 00:00:00+01:00,199220558400000,77.728292,45.446780,36.145436,40.906425,1533.148425,123.175072,77.051861
3,1,2013-11-04 00:00:00+01:00,199233000000000,104.793806,54.821018,67.898464,70.399418,1404.813593,159.614824,138.297882
4,1,2013-11-05 00:00:00+01:00,199245441600000,97.425105,46.607029,68.735213,70.766221,1518.090111,144.032134,139.501434

In [40]:
cdfD["timeInterval1"] = pd.to_datetime(cdfD['timeIntervalts']).dt.tz_convert('CET')
# (cdfD["timeIntervalts"].astype(int)// 10**9).astype('U10')
cdfD.head()
# pd.to_datetime(df['timeInterval'],unit='ms').dt.tz_localize('UTC').dt.tz_convert('CET')

,cellId,timeIntervalts,timeInterval,SMSin,SMSout,callIn,callOut,internet,SMS,call,timeInterval1
0,1,2013-11-01 00:00:00+01:00,199195675200000,78.709755,45.886570,41.108567,48.245378,1507.048349,124.596325,89.353945,2013-11-01 00:00:00+01:00
1,1,2013-11-02 00:00:00+01:00,199208116800000,86.415810,43.875946,47.891016,53.590637,1515.641856,130.291756,101.481653,2013-11-02 00:00:00+01:00
2,1,2013-11-03 00:00:00+01:00,199220558400000,77.728292,45.446780,36.145436,40.906425,1533.148425,123.175072,77.051861,2013-11-03 00:00:00+01:00
3,1,2013-11-04 00:00:00+01:00,199233000000000,104.793806,54.821018,67.898464,70.399418,1404.813593,159.614824,138.297882,2013-11-04 00:00:00+01:00
4,1,2013-11-05 00:00:00+01:00,199245441600000,97.425105,46.607029,68.735213,70.766221,1518.090111,144.032134,139.501434,2013-11-05 00:00:00+01:00

In [41]:
cdfD2 = cdfD[['cellId', 'timeInterval1', 'SMSin', 'SMSout', 'callIn',
       'callOut', 'internet', 'SMS', 'call']]

In [42]:
# cdfD2['timeInterval1'].unique()
cdfD2["timeIntervalts"] = (cdfD2["timeInterval1"].astype(int)// 10**9).astype('U10')
cdfD2.head()

C:\Users\kisha\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,cellId,timeInterval1,SMSin,SMSout,callIn,callOut,internet,SMS,call,timeIntervalts
0,1,2013-11-01 00:00:00+01:00,78.709755,45.886570,41.108567,48.245378,1507.048349,124.596325,89.353945,1383260400
1,1,2013-11-02 00:00:00+01:00,86.415810,43.875946,47.891016,53.590637,1515.641856,130.291756,101.481653,1383346800
2,1,2013-11-03 00:00:00+01:00,77.728292,45.446780,36.145436,40.906425,1533.148425,123.175072,77.051861,1383433200
3,1,2013-11-04 00:00:00+01:00,104.793806,54.821018,67.898464,70.399418,1404.813593,159.614824,138.297882,1383519600
4,1,2013-11-05 00:00:00+01:00,97.425105,46.607029,68.735213,70.766221,1518.090111,144.032134,139.501434,1383606000

In [43]:
%%time
data_to_color = "SMS"
cells = list(cdfD2["cellId"].unique())
dates = list(cdfD2["timeIntervalts"].unique())
colors = get_hex_colors.get_hex_colors(cdfD2, data_to_color, cmap = matplotlib.cm.cool)#, log = True) # color dict that get's created from our get_hex_colors based on the values you want to plot
cdfD2["COLORS"] = cdfD2[data_to_color].map(colors) # create a colum in the df so that we can iterate and create the styledict

Wall time: 2min 58s

In [44]:
%%time
styledict = {}
for cell in cells:
    #print(row)
    styledict[str(cell)] = {row['timeIntervalts']: {'color': row['COLORS'],
                                   'opacity': 0.6,'weight': 0.4} 
                            for index, row in cdfD2[cdfD2['cellId']==cell].iterrows()}

Wall time: 2min 53s

In [ ]:
# creates and renders the Folium map
m = folium.Map(location=[45.46440063879739, 9.194880739442098],tiles="Stamen Toner" #"cartodbpositron"
               , zoom_start=12)

g = TimeSliderChoropleth(
    gdf.set_index("cellId").to_json(), # get's the coordinates for each id 
    styledict = styledict, # styledict contains for each id the timestamp and the color to plot.
    name = 'TimeSlider',
    overlay = False
)

m.add_child(g)
m.save('TimeSliderChoropleth3.html')

m